name: Build Android APK

on:
  push:
    branches:
      - main  # Sesuaikan jika branch utama Anda bernama master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Menggunakan JDK 17 Resmi & Stabil
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Generate Gradle Wrapper
        run: gradle wrapper

      - name: Make Gradle executable
        run: chmod +x gradlew

      # Membuat file debug.keystore otomatis agar validasi awal Gradle lolos
      - name: Generate Dummy Debug Keystore
        run: |
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

      # Mem-build APK Release dengan isolasi JVM penuh agar KSP aman dari error grafis
      - name: Build Release APK
        run: ./gradlew assembleRelease --no-daemon
        env:
          GRADLE_OPTS: "-Djava.awt.headless=true -Dorg.gradle.jvmargs=-Djava.awt.headless=true"

      # Menandatangani APK menggunakan GitHub Secrets asli Anda
      - name: Sign Release APK
        uses: r0adkll/sign-android-release@v1.0.4
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: "35.0.0"
          singleOutputFile: true

      # Mengunggah APK Resmi hasil tanda tangan digital Anda
      - name: Upload Official Release APK
        uses: actions/upload-artifact@v4
        with:
          name: Akbar-Media-Official-Release
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}
